name: mySobrero
description: La nuova app ufficiale del Sobrero per gli Studenti

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1+33

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  http: ^0.12.2
  flutter_custom_tabs: ^0.6.0
  fl_chart: ^0.6.3
  intl: ^0.16.1
  shared_preferences: ^0.5.6
  local_auth: ^0.6.1
  auto_size_text: ^2.1.0
  cached_network_image: ^2.0.0
  image_picker: ^0.6.3+1
  package_info: ^0.4.0+13
  expandable: ^4.0.2
  launch_review: ^2.0.0
  async: ^2.4.0
  flutter_svg: ^0.18.0
  percent_indicator: ^2.1.1
  flutter_spinkit: ^4.1.2
  waterfall_flow: ^0.1.3
  utf: ^0.9.0+5
  animations: ^1.1.1
  quick_actions: ^0.4.0+2
  flutter_html: ^0.11.1
  country_icons: ^1.1.1
  qr_code_scanner:
    git:
      url: git://github.com/juliuscanute/qr_code_scanner.git
  wave: ^0.0.8
  uni_links: ^0.4.0
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  flare_flutter: ^1.8.3
  flutter_tabler_icons: ^1.0.2
  background_fetch: ^0.6.0
  flutter_local_notifications: ^1.4.4+4
  tutorial_coach_mark: ^0.5.1
  native_pdf_view: ^3.8.0
  googleapis: any
  googleapis_auth: any
  device_info: ^0.4.2+9

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  dependency_validator: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/ic_launcher.png
  image_path_ios: assets/icon/ic_launcher_ios.png
  adaptive_icon_background: assets/icon/ic_background.png
  adaptive_icon_foreground: assets/icon/ic_foreground.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
    - i18n/en.json
    - i18n/it.json

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 400
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
